name: provision
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+15
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.1.0
  lottie: ^2.3.2
  fluttertoast: ^8.2.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  connectivity_plus: ^2.3.2
  get_it: ^7.2.0
  dio: ^4.0.4
  hive: ^2.2.3
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  path_provider: ^2.0.13
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.0.1
  dropdown_button2: ^2.0.0
  jwt_decoder: ^2.0.1
  toast: ^0.3.0
  dropdown_search: ^3.0.1
  flutter_keyboard_visibility: ^5.4.0
  image_picker: ^0.8.7+3
  flutter_svg: ^2.0.5
  flutter_dialogs: ^3.0.0
  firebase: ^9.0.3
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/app_logo.png
    - images/provision_logo.png
    - images/sign_up_confirm.png
    - images/sign_out.png
    - images/default_user_image.png
    - images/no internet connection.json
    - images/change_password_done.json
    - images/done_successfully.json
    - images/decline.png
    - images/accept_add.png
    - images/home.png
    - images/explore.png
    - images/menu_icon.png
    - images/user_info.png
    - images/connections.png
    - images/meetings.png
    - images/logout.png
    - images/map_image.png
    - images/facebook_icon.png
    - images/twitter_icon.png
    - images/youtube_icon.png
    - images/linked_in_icon.png
    - images/app_svg_logo.svg
    - images/splash_svg_logo.svg
    - images/service_unavailable.json
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts_assets\Poppins-Regular.ttf
          weight: 900
          style: normal